name: Simple Workflow

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Step 1 - Build
        run: echo "Building the project..."
      
      - name: Step 2 - Test
        run: echo "Running tests..."

      - name: Step 3 - Deploy
        run: echo "Deploying the project..."

      - name: Step 4 - Notify
        run: echo "Notifying stakeholders..."
